name: laundry_service
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity: null
  get: ^4.6.6
  http: null
  intl: ^0.18.0
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.11
  sqflite: ^2.3.2
  google_fonts: 6.1.0
  animated_notch_bottom_bar: ^1.0.3
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4
  share_plus: ^7.2.2
flutter_native_splash:
  color: "#485BC4"
  image: assets/images/splash.png
  android_gravity: fill
  android_12:
    image: assets/images/splash.png
    color: "#485BC4"



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: OverusedGrotesk
      fonts:
        - asset: fonts/ttf/OverusedGrotesk-Black.ttf
        - asset: fonts/ttf/OverusedGrotesk-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/
    - assets/pdfs/

